#!/bin/bash

#This tells the scheduler what account to use.  Do not change.
#PBS -A junzli_flux
#This is the job name.  Feel free to change this at will to whatever you need.
#PBS -N 2018.08.13.bwa_index.rat_genome_01.pbs
#This denotes the queue that the job should be run in.  Do not change if you want to use the flux dedicated nodes
#PBS -q flux
#The next two denotes the email address to send jobs to, and under what conditions to send that email.
#PBS -M hanyou@umich.edu
#This line says (a) send email if the job fails, (b) when the job starts, and (e) when the job ends.
#PBS -m abe
#This line combine e file into o file.
#PBS -j oe
#This line sends all environment variables on the login node.
#PBS -V
#The max for ppn is currently 12, and the max for walltime is 376 hours (or 28 days).
#PBS -l nodes=1:ppn=1,pmem=10gb,walltime=10:00:00
#PBS -l qos=flux
#Your shell script and commands goes here.

cd /scratch/junzli_flux/hanyou/resource/reference/rat_genome_01
bwa index -a bwtsw /scratch/junzli_flux/hanyou/resource/reference/rat_genome_01/rn6.fa

