#!/bin/bash

#PBS -S /bin/bash
#PBS -A ACF-UTHSC0013
#PBS -l nodes=1:ppn=24,walltime=140:00:00
#PBS -m abe 
#PBS -M hanyou@umich.edu 
#PBS -j oe 
#PBS -l partition=monster

cd
. ~/.bashrc
conda activate bionano

mkdir -p /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/hybrid_scaffold/SHR

perl /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/HybridScaffold/09262019/hybridScaffold.pl \
-n /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39695/fasta/95-39695_pseudohap.fasta \
-b /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/de_novo/SHR/SHR/contigs/exp_refineFinal1/EXP_REFINEFINAL1.cmap \
-c /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/HybridScaffold/09262019/hybridScaffold_DLE1_config_monster_1.xml \
-r /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/RefAligner/8949.10020rel/RefAligner \
-o /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/hybrid_scaffold/SHR \
-B 2 \
-N 2 \
-f


