#!/bin/bash

#PBS -S /bin/bash
#PBS -A ACF-UTHSC0013
#PBS -l nodes=1:ppn=24,walltime=140:00:00
#PBS -m abe
#PBS -M hanyou@umich.edu
#PBS -j oe
#PBS -l partition=monster
#PBS -N 2019-10-01_x_supernova_run_mkoutput_general_ut_95-39695.qsub


source /nics/c/home/hanyou/.bashrc
cd

mkdir -p /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39695
cd /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39695

supernova run --id=95-39695 --fastqs=/lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/sequences/95-39695/ --sample=95-39695_S57,95-39695_S58,95-39695_S59,95-39695_S60 --maxreads=1640000000

# maxread = 2.87e9 * 56 / 151 = 1.64e9

mkdir -p fasta
cd fasta

supernova mkoutput --style=pseudohap --asmdir=/lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39695/95-39695/outs/assembly --outprefix=95-39695_pseudohap --minsize=10000 --headers=short



