#!/bin/bash

#PBS -S /bin/bash
#PBS -A ACF-UTHSC0013
#PBS -l nodes=1:ppn=40,walltime=140:00:00
#PBS -m abe
#PBS -M hanyou@umich.edu
#PBS -j oe
#PBS -l partition=general,feature=skylake
#PBS -N 2020-05-21_x_long_ranger_wgs_5739-JL-0040.qsub


source /nics/c/home/hanyou/.bashrc
cd

mkdir -p /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/long_ranger/5739-JL-0040
cd /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/long_ranger/5739-JL-0040

longranger wgs --id=5739-JL-0040 --reference=/lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/references/refdata-mRatNor1_1.curated_primary.20200424 --fastqs=/lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/sequences/5739-JL-0040/ --sample=5739-JL-0040_1,5739-JL-0040_2,5739-JL-0040_3,5739-JL-0040_4 --vcmode=gatk:/lustre/haven/proj/UTHSC0013/UM/apps/gatk_4.0.3.0/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar

