#!/bin/bash                                                                                                                                               

#PBS -S /bin/bash                                                                                                                                          
#PBS -A ACF-UTHSC0013                                                                                                                                      
#PBS -l nodes=1:ppn=24,walltime=140:00:00                                                                                                
#PBS -m abe                                                                                                                                                
#PBS -M hanyou@umich.edu                                                                                                                                   
#PBS -j oe                                                                                                                                                 
#PBS -l partition=monster                                                                                                                   
#PBS -N 2019-11-06_1_bionano_solve_hybrid_scaffold_95-39694.qsub


. ~/.bashrc
conda activate bionano

cd /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39694/fasta
#gunzip 95-39694_pseudohap.fasta.gz

mkdir -p /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/hybrid_scaffold/95-39694

perl /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/HybridScaffold/09262019/hybridScaffold.pl \
-n /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/supernova/95-39694/fasta/95-39694_pseudohap.fasta \
-b /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/data/95-39694/contigs/exp_refineFinal1/EXP_REFINEFINAL1.cmap \
-c /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/HybridScaffold/09262019/hybridScaffold_DLE1_config_monster.xml \
-r /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/RefAligner/8949.10020rel/RefAligner \
-o /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/hybrid_scaffold/95-39694 \
-B 2 \
-N 2 \
-f
#-x \
#-y \
#-m /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/data/95-39694/all.bnx \
#-p /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/Pipeline/09262019 \
#-q /lustre/haven/proj/UTHSC0013/UM/apps/bionano_solve_3.4.1/Solve3.4.1_09262019/RefAligner/8949.10020rel/optArguments_haplotype_DLE1_saphyr_human.xml \
#-e /lustre/haven/proj/UTHSC0013/UM/projects/rat_genome_03/bionano/data/95-39694/contigs/auto_noise/autoNoise1.errbin
